events {}

http {
    resolver 8.8.8.8 ipv6=off valid=60s;

    server {
        listen 80 default_server;
        server_name martintarot.com;

        # --- Projet 1: Martin Dessin ---
        # On gère le cas sans slash final pour éviter la 404
        location /martin-dessin {
            return 301 $scheme://$http_host/martin-dessin/;
        }

        location /martin-dessin/ {
            proxy_pass http://web:8000/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Prefix /martin-dessin;
        }

        # --- Projet 2: Fashion MNIST ---
        location /fashion-mnist {
            return 301 $scheme://$http_host/fashion-mnist/;
        }

        location /fashion-mnist/ {
            proxy_pass https://project.martintarot.com/; 
            proxy_ssl_server_name on;
            proxy_set_header Host project.martintarot.com;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # --- Site principal (GitHub Pages) ---
        # Ici, on n'utilise plus "location /website/". 
        # On met tout à la RACINE pour l'utilisateur.
        location / {
            # Le "/" final après /website/ est ce qui "supprime" le préfixe
            proxy_pass https://mtarotml.github.io/website/; 
            
            proxy_ssl_server_name on;
            proxy_set_header Host mtarotml.github.io;
            
            # Sécurité : On empêche GitHub de rediriger l'utilisateur vers /website/
            proxy_redirect https://mtarotml.github.io/website/ /;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}